import * as T from './vendor/three.module.js';
import {sculpt} from './sculpt.js?v=3';
const canvas=document.querySelector('canvas');
const renderer=new T.WebGLRenderer({canvas,antialias:true,alpha:false});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.05;
const scene=new T.Scene();scene.background=new T.Color('#eee4d3');scene.fog=new T.Fog('#eee4d3',12,28);
const camera=new T.PerspectiveCamera(36,1,.1,60);let yaw=.48,pitch=.12,distance=innerWidth<600?11:8.5,auto=false;
scene.add(new T.HemisphereLight('#fff4dd','#6d664b',2.4));const sun=new T.DirectionalLight('#ffdfad',4);sun.position.set(-4,7,5);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-5,right:5,top:6,bottom:-4});sun.shadow.bias=-.0003;sun.shadow.normalBias=.025;scene.add(sun);const rim=new T.DirectionalLight('#d8e7ff',2);rim.position.set(4,4,-4);scene.add(rim);
// Fine pigment variation is generated as a material texture; the character is actual geometry.
function pigment(color){const c=document.createElement('canvas');c.width=c.height=256;const x=c.getContext('2d');x.fillStyle=color;x.fillRect(0,0,256,256);let seed=17;for(let i=0;i<16000;i++){seed=(seed*1664525+1013904223)>>>0;const a=seed/4294967296;seed=(seed*1664525+1013904223)>>>0;const b=seed/4294967296;x.fillStyle=i%2?'rgba(255,244,205,.035)':'rgba(66,35,18,.035)';x.fillRect(a*256,b*256,1,3)}const tex=new T.CanvasTexture(c);tex.colorSpace=T.SRGBColorSpace;return new T.MeshStandardMaterial({map:tex,roughness:.92});}
const orange=pigment('#bf642d'),light=pigment('#dc843e'),cream=pigment('#eee0b8'),dark=pigment('#44352b'),inner=pigment('#7e4835'),noseMat=new T.MeshStandardMaterial({color:'#272320',roughness:.45}),eyeMat=new T.MeshStandardMaterial({color:'#281c12',roughness:.18}),iris=new T.MeshStandardMaterial({color:'#ad6b29',roughness:.4}),white=new T.MeshStandardMaterial({color:'#fff8e4',roughness:.4}),mouthMat=new T.MeshStandardMaterial({color:'#402721',roughness:1});
const fox=new T.Group();scene.add(fox);const body=new T.Group();fox.add(body);
function ell(parent,mat,p,s){const m=new T.Mesh(new T.SphereGeometry(1,40,28),mat);m.position.set(...p);m.scale.set(...s);m.castShadow=true;m.receiveShadow=true;parent.add(m);return m;}
function tapered(parent,a,b,r1,r2,mat){const av=new T.Vector3(...a),bv=new T.Vector3(...b),d=bv.clone().sub(av);const m=new T.Mesh(new T.CylinderGeometry(r2,r1,d.length(),24),mat);m.position.copy(av.add(bv).multiplyScalar(.5));m.quaternion.setFromUnitVectors(new T.Vector3(0,1,0),d.normalize());m.castShadow=true;parent.add(m);return m;}
const rust=new T.Color('#c77538'),ivory=new T.Color('#e9d9b7'),sock=new T.Color('#4b382c');
const parts=[[0,1.38,-.22,.39,.58,.72],[0,1.79,.23,.32,.56,.33],[0,1.99,.28,.31,.33,.30]];
for(const side of [-1,1]){const x=side*.28;parts.push([x,1.06,-.65,.22,.39,.26],[x,.66,-.71,.10,.35,.11],[x,.29,-.65,.076,.23,.09],[x,.10,-.55,.105,.09,.19],[x,1.08,.29,.10,.47,.12],[x,.57,.34,.075,.35,.085],[x,.19,.39,.07,.15,.085],[x,.08,.48,.10,.075,.18]);}
const torso=sculpt(parts,[-.7,-.02,-1.1,.7,2.36,.7],.032,(x,y,z)=>{let c=rust.clone();const chest=Math.max(0,Math.min(1,(z-.36)*12))*Math.max(0,1-Math.abs(x)/.27);c.lerp(ivory,chest);c.lerp(sock,Math.max(0,Math.min(1,(.54-y)*6)));return c;});body.add(torso);
const head=new T.Group();head.position.set(0,2.16,.35);body.add(head);const face=sculpt([[0,.10,-.04,.43,.35,.32],[0,-.075,.25,.29,.18,.31],[0,-.12,.47,.17,.115,.25],[-.28,-.07,.09,.22,.16,.22],[.28,-.07,.09,.22,.16,.22]],[-.58,-.32,-.4,.58,.5,.77],.023,(x,y,z)=>{const c=rust.clone();const line=-.015+.16*Math.abs(x);return c.lerp(ivory,Math.max(0,Math.min(1,(line-y)*30)));});head.add(face);
ell(head,noseMat,[0,-.115,.705],[.082,.054,.053]);const jaw=new T.Group();jaw.position.set(0,-.18,.18);head.add(jaw);ell(jaw,cream,[0,-.035,.25],[.18,.068,.30]);ell(jaw,mouthMat,[0,.012,.28],[.14,.013,.24]);
for(const side of [-1,1]){const e=new T.Group();e.position.set(side*.23,.16,.267);e.rotation.y=side*.32;head.add(e);ell(e,dark,[0,0,0],[.092,.065,.018]);ell(e,iris,[0,0,.013],[.048,.049,.012]);ell(e,eyeMat,[0,0,.024],[.025,.043,.008]);ell(e,white,[-.017,.02,.033],[.01,.011,.006]);const lid=ell(e,light,[0,.035,.015],[.132,.02,.055]);lid.visible=false;e.userData.lid=lid;head.userData.eyes??=[];head.userData.eyes.push(e);
 const ear=new T.Group();ear.position.set(side*.31,.40,-.03);ear.rotation.z=-side*.34;head.add(ear);const shape=new T.Shape();shape.moveTo(-.19,0);shape.quadraticCurveTo(-.23,.33,0,.67);shape.quadraticCurveTo(.23,.33,.19,0);shape.closePath();const geo=new T.ExtrudeGeometry(shape,{depth:.055,bevelEnabled:true,bevelSize:.018,bevelThickness:.015,bevelSegments:3,steps:1,curveSegments:18});const mesh=new T.Mesh(geo,orange);mesh.castShadow=true;ear.add(mesh);const panel=new T.Mesh(new T.ShapeGeometry(shape,24),cream);panel.scale.set(.68,.78,1);panel.position.set(0,.055,.075);ear.add(panel);const inset=new T.Mesh(new T.ShapeGeometry(shape,24),cream);inset.scale.set(.37,.63,1);inset.position.set(0,.065,.155);inset.visible=false;ear.add(inset);head.userData.ears??=[];head.userData.ears.push(ear);}
const tail=new T.Group();tail.position.set(0,1.06,-.80);body.add(tail);
const path=new T.CatmullRomCurve3([new T.Vector3(0,0,0),new T.Vector3(.35,-.18,-.42),new T.Vector3(.77,-.02,-.76),new T.Vector3(1.03,.41,-.7),new T.Vector3(1.04,.85,-.48)]);
const tg=new T.TubeGeometry(path,64,1,24,false),p=tg.attributes.position;for(let i=0;i<p.count;i++){const row=Math.floor(i/25),u=row/64,center=path.getPointAt(u),radius=.035+.29*Math.pow(Math.sin(Math.PI*u),.8);const v=new T.Vector3().fromBufferAttribute(p,i).sub(center).multiplyScalar(radius).add(center);p.setXYZ(i,v.x,v.y,v.z)}tg.clearGroups();for(let i=0;i<64;i++)tg.addGroup(i*24*6,24*6,i>43?1:0);tg.computeVertexNormals();const tm=new T.Mesh(tg,[orange,cream]);tm.castShadow=true;tail.add(tm);
const ground=new T.Mesh(new T.CircleGeometry(100,64),new T.MeshStandardMaterial({color:'#ded3b8',roughness:1}));ground.rotation.x=-Math.PI/2;ground.position.y=-.015;ground.receiveShadow=true;scene.add(ground);
// Restrained meadow accents frame the turntable without hiding its silhouette.
const straw=new T.MeshStandardMaterial({color:'#bfa26a',roughness:1});for(let i=0;i<32;i++){const a=i*2.39996,r=2.4+(i%5)*.17,x=Math.cos(a)*r,z=Math.sin(a)*r;if(z>1.3)continue;const h=.28+(i%7)*.055;tapered(scene,[x,0,z],[x+.06,h,z],.008,.004,straw);ell(scene,straw,[x+.06,h,z],[.035,.1,.025]);}
let drag=false,px=0,py=0;canvas.onpointerdown=e=>{drag=true;px=e.clientX;py=e.clientY;canvas.setPointerCapture(e.pointerId)};canvas.onpointermove=e=>{if(!drag)return;yaw-=(e.clientX-px)*.009;pitch=Math.max(-.1,Math.min(.7,pitch+(e.clientY-py)*.005));px=e.clientX;py=e.clientY};canvas.onpointerup=()=>drag=false;canvas.onpointercancel=()=>drag=false;canvas.onwheel=e=>{e.preventDefault();distance=Math.max(5,Math.min(13,distance+e.deltaY*.008))};document.querySelector('#front').onclick=()=>{yaw=0;pitch=.12};document.querySelector('#side').onclick=()=>{yaw=1.57;pitch=.12};document.querySelector('#rotate').onclick=e=>{auto=!auto;e.target.classList.toggle('on',auto)};
let ctx,source,analyser,data,energy=0;const speak=document.querySelector('#speak');function stop(){if(source){source.onended=null;try{source.stop()}catch{}source.disconnect();source=null}analyser?.disconnect();analyser=null;energy=0;speak.textContent='听它说话'}speak.onclick=async()=>{if(source){stop();return}try{ctx??=new AudioContext();await ctx.resume();speak.disabled=true;const res=await fetch('./sample.wav');if(!res.ok)throw Error();const b=await ctx.decodeAudioData(await res.arrayBuffer());source=ctx.createBufferSource();source.buffer=b;analyser=ctx.createAnalyser();analyser.fftSize=256;data=new Float32Array(256);source.connect(analyser);analyser.connect(ctx.destination);source.onended=stop;source.start();speak.textContent='停止说话'}catch{document.querySelector('#note').textContent='声音加载失败，请重试'}finally{speak.disabled=false}};
let last=0;function animate(ms){const t=ms/1000,dt=Math.min(.05,t-last);last=t;if(auto&&!drag)yaw+=dt*.22;if(analyser){analyser.getFloatTimeDomainData(data);const rms=Math.sqrt(data.reduce((s,x)=>s+x*x,0)/data.length);energy=energy*.6+Math.min(.65,rms*3)*.4;}jaw.rotation.x=energy;torso.scale.y=1+.007*Math.sin(t*1.8);head.rotation.y=.06*Math.sin(t*.65);head.rotation.z=.025*Math.sin(t*.8);head.rotation.x=.018*Math.sin(t*1.4);tail.rotation.z=.09*Math.sin(t*1.15);tail.rotation.y=.12*Math.sin(t*.8);head.userData.ears.forEach((e,i)=>e.rotation.x=.035*Math.sin(t*1.3+i));const blink=Math.pow(Math.max(0,Math.cos(t*1.65)),40);head.userData.eyes.forEach(e=>{e.scale.y=1-.82*blink});camera.position.set(Math.sin(yaw)*distance,1.5+Math.sin(pitch)*distance,Math.cos(yaw)*distance);camera.lookAt(0,1.55,0);renderer.render(scene,camera);requestAnimationFrame(animate)}function resize(){renderer.setSize(innerWidth,innerHeight,false);camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix()}addEventListener('resize',resize);addEventListener('pagehide',stop);resize();requestAnimationFrame(animate);
