import {LipTimeline} from './lip-timeline.js';
const mouth=document.querySelector('#mouth'),tongue=document.querySelector('#tongue'),note=document.querySelector('#note .badge'),play=document.querySelector('#speak');
let context,source,timeline,buffer,cues;
const mapping={A:'closed',B:'wide',C:'open',D:'open',E:'round',F:'round',G:'labiodental',H:'open',X:'rest'};
function pose(w){const open=(w.open||0)*18+(w.wide||0)*9+(w.round||0)*13+(w.labiodental||0)*4;const width=22+(w.wide||0)*7-(w.round||0)*7;if(open<1){mouth.setAttribute('d','');tongue.setAttribute('d','');return;}mouth.setAttribute('d',`M ${369-width} 537 Q 369 548 ${369+width} 537 Q ${369+width-2} ${545+open} 369 ${546+open} Q ${369-width+2} ${545+open} ${369-width} 537 Z`);tongue.setAttribute('d',open>7?`M 357 ${541+open} Q 369 ${536+open} 381 ${541+open} Q 370 ${548+open} 357 ${541+open} Z`:'');}
function stop(){if(source){source.onended=null;source.stop();source=null;}timeline?.stop();play.disabled=false;pose({});}
document.querySelector('#stop').onclick=()=>{stop();note.textContent='我在这里，听你慢慢说。';};
play.onclick=async()=>{stop();play.disabled=true;try{context??=new AudioContext();await context.resume();if(!buffer){const [wav,data]=await Promise.all([fetch('./sample.wav').then(r=>r.arrayBuffer()),fetch('./sample-mouth-cues.json').then(r=>r.json())]);buffer=await context.decodeAudioData(wav);cues=data.mouthCues.map(c=>({...c,shape:mapping[c.value]}));}source=context.createBufferSource();source.buffer=buffer;source.connect(context.destination);timeline=new LipTimeline(context,pose);const start=context.currentTime+.05;timeline.start(cues,start);source.onended=()=>{source=null;timeline.stop();play.disabled=false;note.textContent='我在这里，听你慢慢说。';};source.start(start);note.textContent='狐狸正在说话…';}catch(e){stop();note.textContent='试听加载失败，请重试。';}};
addEventListener('pointermove',e=>{document.documentElement.style.setProperty('--px',`${(e.clientX/innerWidth-.5)*-9}px`);document.documentElement.style.setProperty('--py',`${(e.clientY/innerHeight-.5)*-5}px`);});addEventListener('pagehide',stop);
