import * as T from './vendor/three.module.js';
import {LipTimeline} from './lip-timeline.js';
import {GLTFLoader} from './vendor/GLTFLoader.js';
const canvas=document.querySelector('canvas'),note=document.querySelector('#note');
const renderer=new T.WebGLRenderer({canvas,antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.05;
const scene=new T.Scene();scene.background=new T.Color('#e9e3d8');const camera=new T.PerspectiveCamera(34,1,.1,50);let yaw=.45,pitch=.13,distance=innerWidth<600?10:8,auto=false,model,head,jaw,tail,face,timeline;
scene.add(new T.HemisphereLight('#fff7e8','#8a8b78',2));for(const [position,color,power] of [[[4,6,4],'#fff0d8',3],[[-4,3,1],'#e5eeff',1],[[2,4,-4],'#ffe4be',2]]){const l=new T.DirectionalLight(color,power);l.position.set(...position);if(power===3){l.castShadow=true;l.shadow.mapSize.set(2048,2048);Object.assign(l.shadow.camera,{left:-4,right:4,top:5,bottom:-4});l.shadow.normalBias=.035}scene.add(l)}
const ground=new T.Mesh(new T.PlaneGeometry(200,200),new T.MeshStandardMaterial({color:'#d8d2c6',roughness:1}));ground.rotation.x=-Math.PI/2;ground.position.y=-.01;ground.receiveShadow=true;scene.add(ground);
note.textContent='正在加载原创狐狸模型…';
new GLTFLoader().load('./original-fox.glb?v=5',g=>{model=g.scene;scene.add(model);model.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true}if(o.name==='Face')face=o;if(o.name==='Head')head=o;if(o.name==='Jaw')jaw=o;if(o.name==='Tail')tail=o});note.textContent='原创模型修订中 · 音频分析嘴型样片 · 中文准确度仍需校正'},undefined,()=>note.textContent='模型加载失败，请刷新');
let dragging=false,px=0,py=0;canvas.onpointerdown=e=>{dragging=true;px=e.clientX;py=e.clientY;canvas.setPointerCapture(e.pointerId)};canvas.onpointermove=e=>{if(!dragging)return;yaw-=(e.clientX-px)*.009;pitch=Math.max(-.1,Math.min(.7,pitch+(e.clientY-py)*.005));px=e.clientX;py=e.clientY};canvas.onpointerup=()=>dragging=false;canvas.onpointercancel=()=>dragging=false;canvas.onwheel=e=>{e.preventDefault();distance=Math.max(4.5,Math.min(14,distance+e.deltaY*.008))};let showFur=true;document.querySelector('#back').onclick=()=>yaw=Math.PI;document.querySelector('#fur').onclick=e=>{showFur=!showFur;model?.traverse(o=>{if(o.name.includes('directionalfur')||o.name.includes('directional_fur')||o.name.includes('directional fur'))o.visible=showFur});e.target.textContent=showFur?'隐藏毛发':'显示毛发'};document.querySelector('#front').onclick=()=>yaw=0;document.querySelector('#side').onclick=()=>yaw=1.57;document.querySelector('#rotate').onclick=e=>{auto=!auto;e.target.classList.toggle('on',auto)};
let ctx,src,analyser,samples,energy=0;const button=document.querySelector('#speak');function stop(){timeline?.stop();if(src){src.onended=null;try{src.stop()}catch{}src.disconnect();src=null}analyser?.disconnect();analyser=null;energy=0;button.textContent='听它说话'}button.onclick=async()=>{if(src){stop();return}try{button.disabled=true;ctx??=new AudioContext();await ctx.resume();const r=await fetch('./sample.wav');if(!r.ok)throw Error();const b=await ctx.decodeAudioData(await r.arrayBuffer());src=ctx.createBufferSource();src.buffer=b;analyser=ctx.createAnalyser();analyser.fftSize=256;samples=new Float32Array(256);src.connect(analyser);analyser.connect(ctx.destination);src.onended=stop;
 const cueResponse=await fetch('./sample-mouth-cues.json');if(!cueResponse.ok)throw Error('Missing alignment');const cueData=await cueResponse.json();
 const mapping={A:'closed',B:'wide',C:'open',D:'open',E:'round',F:'round',G:'labiodental',H:'open',X:'rest'};
 timeline=new LipTimeline(ctx,w=>{if(jaw)jaw.rotation.x=.24*w.open+.09*w.wide+.13*w.round+.04*w.labiodental;
 if(face?.morphTargetDictionary){face.morphTargetInfluences[face.morphTargetDictionary.MouthWide]=w.wide*.75;face.morphTargetInfluences[face.morphTargetDictionary.MouthRound]=w.round*.85;}});
 const at=ctx.currentTime+.08;timeline.start(cueData.mouthCues.map(c=>({start:c.start,end:c.end,shape:mapping[c.value]||'rest'})),at);src.start(at);button.textContent='停止说话'}catch{stop();note.textContent='声音或口型数据加载失败'}finally{button.disabled=false}};
let last=0;function render(ms){const t=ms/1000,dt=Math.min(.05,t-last);last=t;if(auto&&!dragging)yaw+=dt*.22;if(analyser){analyser.getFloatTimeDomainData(samples);energy=.6*energy+.4*Math.min(.4,Math.sqrt(samples.reduce((s,v)=>s+v*v,0)/256)*2.7)}if(head){head.rotation.y=.035*Math.sin(t*.8);head.rotation.z=.017*Math.sin(t*.7)}if(tail)tail.rotation.y=.07*Math.sin(t);camera.position.set(Math.sin(yaw)*distance,1.5+Math.sin(pitch)*distance,Math.cos(yaw)*distance);camera.lookAt(.2,1.5,0);renderer.render(scene,camera);requestAnimationFrame(render)}function resize(){renderer.setSize(innerWidth,innerHeight,false);camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix()}addEventListener('resize',resize);addEventListener('pagehide',stop);resize();requestAnimationFrame(render);
