import * as T from './vendor/three.module.js';
export function sculpt(parts,bounds,step,paint){
 const blend=(a,b,k=.105)=>{const h=Math.max(k-Math.abs(a-b),0)/k;return Math.min(a,b)-h*h*k*.25};
 const field=(x,y,z)=>parts.reduce((d,p)=>blend(d,(Math.hypot((x-p[0])/p[3],(y-p[1])/p[4],(z-p[2])/p[5])-1)*Math.min(p[3],p[4],p[5])),10);
 const pos=[],norm=[],col=[],corners=[[0,0,0],[1,0,0],[1,1,0],[0,1,0],[0,0,1],[1,0,1],[1,1,1],[0,1,1]],tet=[[0,5,1,6],[0,1,2,6],[0,2,3,6],[0,3,7,6],[0,7,4,6],[0,4,5,6]];
 function vertex(v){pos.push(...v);const e=.001,n=new T.Vector3(field(v[0]+e,v[1],v[2])-field(v[0]-e,v[1],v[2]),field(v[0],v[1]+e,v[2])-field(v[0],v[1]-e,v[2]),field(v[0],v[1],v[2]+e)-field(v[0],v[1],v[2]-e)).normalize();norm.push(n.x,n.y,n.z);const c=paint(...v);col.push(c.r,c.g,c.b)}
 for(let x=bounds[0];x<bounds[3];x+=step)for(let y=bounds[1];y<bounds[4];y+=step)for(let z=bounds[2];z<bounds[5];z+=step){const vs=corners.map(c=>[x+c[0]*step,y+c[1]*step,z+c[2]*step]),ds=vs.map(v=>field(...v));if(ds.every(d=>d>0)||ds.every(d=>d<0))continue;for(const ids of tet){const inside=ids.filter(i=>ds[i]<0),outside=ids.filter(i=>ds[i]>=0);if(!inside.length||!outside.length)continue;const edge=(a,b)=>{const f=ds[a]/(ds[a]-ds[b]);return vs[a].map((v,k)=>v+(vs[b][k]-v)*f)};let tri=[];if(inside.length===1)tri=[outside.map(i=>edge(inside[0],i))];else if(inside.length===3)tri=[inside.map(i=>edge(outside[0],i)).reverse()];else{const [a,b]=inside,[c,d]=outside;const ac=edge(a,c),ad=edge(a,d),bc=edge(b,c),bd=edge(b,d);tri=[[ac,ad,bc],[ad,bd,bc]]}for(const tr of tri){const a=new T.Vector3(...tr[0]),b=new T.Vector3(...tr[1]),c=new T.Vector3(...tr[2]),n=b.sub(a).cross(c.sub(a)).normalize(),center=tr[0].map((v,k)=>(v+tr[1][k]+tr[2][k])/3),e=.001;if(field(center[0]+n.x*e,center[1]+n.y*e,center[2]+n.z*e)<field(...center))tr.reverse();for(const v of tr)vertex(v)}}}
 const g=new T.BufferGeometry();g.setAttribute('position',new T.Float32BufferAttribute(pos,3));g.setAttribute('normal',new T.Float32BufferAttribute(norm,3));g.setAttribute('color',new T.Float32BufferAttribute(col,3));const m=new T.Mesh(g,new T.MeshStandardMaterial({vertexColors:true,roughness:.93,side:T.FrontSide}));m.castShadow=true;m.receiveShadow=true;return m;
}
